# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://getpoole.com
paginate:         1
baseurl:          http://rkwrd.github.io/poole/
author:
  name:           AL
  url:            http://www.google.com
  email:          plonk@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
